const details = [
  { src: "/images/m1.png", title: "اسباب بازی" },
  { src: "/images/m2.png", title: "طلا و نقره" },
  { src: "/images/m3.png", title: "ورزش و سفر" },
  { src: "/images/m4.png", title: "کارت هدیه" },
  { src: "/images/m5.png", title: "محصولات بومی" },
  { src: "/images/m6.png", title: "کالا خوراکی" },
  { src: "/images/m7.png", title: "خودرو" },
  { src: "/images/m8.png", title: "آرایشی بهداشتی" },
  { src: "/images/m9.png", title: "لوازم خانه" },
  { src: "/images/m10.png", title: "کالای دیجیتال" },
  { src: "/images/m11.png", title: "لوازم تحریر" },
  { src: "/images/m12.png", title: "مد و پوشاک" },
  { src: "/images/m13.png", title: "تجهیزات پزشکی و سلامت" },
  { src: "/images/m14.png", title: "ابزار آلات" },
  { src: "/images/t1.png" },
  { src: "/images/t2.png" },
  { src: "/images/t3.png" },
  { src: "/images/t4.png" },
];
const categorySlideShow = [
  { src: "/images/b1.png" },
  { src: "/images/b2.png" },
  { src: "/images/b3.png" },
  { src: "/images/b4.png" },
  { src: "/images/b5.png" },
  { src: "/images/b6.png" },
  { src: "/images/b7.png" },
  { src: "/images/b8.png" },
  { src: "/images/b9.png" },
  { src: "/images/b10.png" },
  { src: "/images/b11.png" },
];
export { details, categorySlideShow };
