const details = [
  { title: "کیف و کاور گوشی" },
  { title: "گوشی موبایل" },
  { title: "هدفون هدستو هندزفری" },
  { title: "ساعت هوشمند" },

  { title: "لپ تاپ و الترا بوک" },
  { title: "رنگ مو" },
  { title: "جوراب مردانه" },
];
const imgs = [
  { src: "/images/p2.png" },
  { src: "/images/p3.png" },
  { src: "/images/p4.png" },
  { src: "/images/p5.png" },
  { src: "/images/p6.png" },
  { src: "/images/p7.png" },
  { src: "/images/p8.png" },
  { src: "/images/p9.png" },
  { src: "/images/p10.png" },
  { src: "/images/p11.png" },
  { src: "/images/p12.png" },
  { src: "/images/p13.png" },
  { src: "/images/p14.png" },
  { src: "/images/p15.png" },
  { src: "/images/p16.png" },
  { src: "/images/p17.png" },
  { src: "/images/p21.png" },
  { src: "/images/p22.png" },
  { src: "/images/p23.png" },
  { src: "/images/p24.png" },
  { src: "/images/p25.png" },
  { src: "/images/p26.png" },
  { src: "/images/p27.png" },
  { src: "/images/p28.png" },
  { src: "/images/p29.jpg" },
  { src: "/images/p30.png" },
  { src: "/images/p31.png" },
  { src: "/images/p32.png" },
];
const mostSale = [
  {
    src: "/images/p18.png",
    count: "1",
    desc: "پنیر سفید ایرانی پگاه- 400گرم",
  },
  { src: "/images/p19.png", count: "2", desc: "کاغذ A4 کپی مکس" },
  { src: "/images/p20.png", count: "3", desc: "صابون گلنار مدل روغن نارگیل" },
];
export { details, imgs, mostSale };
